name = "JuTrack"
uuid = "e0df4a49-1e16-4cdd-8109-614ef0534f02"
authors = ["Jinyu Wan <wan@frib.msu.edu>"]
version = "1.0.0-DEV"

[deps]
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
