name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10.4'  

    - name: Install dependencies
      run: julia --project=docs -e 'using Pkg; Pkg.instantiate();'
    - name: Install Documenter
      run: julia --project=docs -e 'using Pkg; Pkg.add("Documenter")'
    - name: Install JuTrack
      run: julia --project=docs -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/MSU-Beam-Dynamics/JuTrack.jl")
    - name: Build documentation
      run: julia --project=docs docs/make.jl

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
